#!/usr/bin/env bash
# Generated by packages/swarm/scripts/sync-bridge-shims.ts; edit the canonical bridge.
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="${ZOUROBOROS_WORKSPACE_ROOT:-$(cd -- "$SCRIPT_DIR/../../.." && pwd)}"
BRIDGE="$WORKSPACE_ROOT/packages/swarm/src/executor/bridges/gemini-bridge.sh"
if [[ ! -f "$BRIDGE" ]]; then
  echo "BRIDGE_ERROR: canonical gemini bridge missing; use the complete workspace or set ZOUROBOROS_WORKSPACE_ROOT" >&2
  exit 127
fi
exec bash "$BRIDGE" "$@"
