#!/usr/bin/env bun
// Generated by packages/swarm/scripts/sync-runtime-copies.ts; edit packages/swarm/src/executor/register.ts.
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const roots: string[] = [];
for (let root = dirname(fileURLToPath(import.meta.url)); ; root = dirname(root)) {
  roots.push(root);
  if (dirname(root) === root) break;
}
if (process.env.ZOUROBOROS_WORKSPACE_ROOT) roots.push(process.env.ZOUROBOROS_WORKSPACE_ROOT);
const target = roots.map(root => join(root, 'packages/swarm/src/executor/register.ts'))
  .find(path => existsSync(path) && pathToFileURL(path).href !== import.meta.url);
if (!target) throw new Error('Canonical swarm runtime missing: use the complete workspace or set ZOUROBOROS_WORKSPACE_ROOT');
await import(pathToFileURL(target).href);
